server:
  port: 8080

spring:
  application:
    name: sispj

---

spring:
  profiles: local

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: sispj
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://sispj-db:5432/sispj?currentSchema=sispj'
    username: postgres
    password: postgres
  liquibase:
    default-schema: sispj
    liquibase-schema: sispj

sispj:
  security:
    secret: "${SECURITY_SECRET}"
    timeout: 600000
    refresh-timeout: 1200000
    #timeout: 20000
    #refresh-timeout: 60000
  file-upload-token: "${FILE_UPLOAD_TOKEN}"
  allowed-origin: 'http://localhost:4200'
  budget-report-logo: 'budget_report_logo.png'
---
spring:
  profiles: test

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://sispj-db:5432/sispj?currentSchema=public'
    username: postgres
    password: postgres
  liquibase:
    default-schema: public
    liquibase-schema: public

sispj:
  security:
    secret: "abc"
    timeout: 600000
    refresh-timeout: 1200000
  file-upload-token: "def"
  allowed-origin: 'http://localhost:4200'
  budget-report-logo: 'budget_report_logo.png'
---

spring:
  profiles: staging

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DATABASE_JDBC_URL}"
    username: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
  liquibase:
    default-schema: public
    liquibase-schema: public

sispj:
  security:
    secret: "${SECURITY_SECRET}"
    timeout: 7200000
    refresh-timeout: 28800000
  file-upload-token: "${FILE_UPLOAD_TOKEN}"
  allowed-origin: "${ALLOWED_ORIGIN}"
  budget-report-logo: 'budget_report_logo.png'

---

spring:
  profiles: staging-mf

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DATABASE_JDBC_URL}"
    username: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
  liquibase:
    default-schema: public
    liquibase-schema: public

sispj:
  security:
    secret: "${SECURITY_SECRET}"
    timeout: 7200000
    refresh-timeout: 28800000
  file-upload-token: "${FILE_UPLOAD_TOKEN}"
  allowed-origin: "${ALLOWED_ORIGIN}"
  budget-report-logo: 'budget_report_logo.png'